Update proxy.rst
Security-Onion-Solutions/securityonion-docs pull request #41
Opened 2021-04-07 18:39 UTC by gebhard73

Clarification about environment variables when running commands as root.

2021-04-07 19:11 UTC, rwwiv requested changes

2021-04-07 19:11 UTC, rwwiv commented on proxy.rst
> +It won't work if you do a ``sudo su -`` followed by a ``so-rule-update``.
`sudo su -` ignores `/etc/environment`, but `sudo su` does not.
 
I would probably reword this as:
```rst
.. warning::
	Using ``sudo su -`` will ignore ``/etc/environment``, instead use ``sudo su`` if you need to operate as root.
```

2021-04-07 20:13 UTC, gebhard73 commented
Thanks, this explains it better.

2021-04-25 09:36 UTC, gebhard73 reviewed
Thanks, this explains it better.

2021-05-04 11:21 UTC, merged